name: Build and Deploy

on: 
  push: 
    # branch: main

jobs: 
  build: 
  runs-on: ubuntu-latest
    steps: 
      - name: Checkout main branch
      uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

  # publish: 
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps: 
  #     - name: Deploy app
  #   uses: 
  #   with: 
  #     host: 
  #     key: 
  #     username: 
